//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IJSDIJ5;Initial Catalog=BDBubbleHouse;Persist Security Info=T" +
            "rue;User ID=Jurguen;Password=Monge2909-;TrustServerCertificate=True")]
        public string BDBubbleHouseConnectionString {
            get {
                return ((string)(this["BDBubbleHouseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-JBPH1CV\\SQLEXPRESS;Initial Catalog=BDBubbleHouse;User ID=Bubb" +
            "leHouse;Password=123;Encrypt=False;TrustServerCertificate=True")]
        public string BDBubbleHouseConnectionString1 {
            get {
                return ((string)(this["BDBubbleHouseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IJSDIJ5;Initial Catalog=BDBubbleHouse;Persist Security Info=T" +
            "rue;User ID=Jurguen;Password=Monge2909-;Encrypt=True;TrustServerCertificate=True" +
            "")]
        public string BDBubbleHouseConnectionString2 {
            get {
                return ((string)(this["BDBubbleHouseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Fernanda\\SQLEXPRESS;Initial Catalog=BDBubbleHouse;Integrated Security" +
            "=True;Encrypt=True;TrustServerCertificate=True")]
        public string BDBubbleHouseConnectionString3 {
            get {
                return ((string)(this["BDBubbleHouseConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AR7N3CH;Initial Catalog=BDBubbleHouse;Persist Security Info=T" +
            "rue;User ID=Moviles;Password=123;Encrypt=False;TrustServerCertificate=True")]
        public string BDBubbleHouseConnectionString4 {
            get {
                return ((string)(this["BDBubbleHouseConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AR7N3CH;Initial Catalog=BDBubbleHouse;Persist Security Info=T" +
            "rue;User ID=Moviles;Encrypt=False;TrustServerCertificate=True")]
        public string BDBubbleHouseConnectionString5 {
            get {
                return ((string)(this["BDBubbleHouseConnectionString5"]));
            }
        }
    }
}
