
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Obtener_Facturas_No_Pagadas
AS
BEGIN
    -- Seleccionar todas las facturas no pagadas
    SELECT F.ID_FACTURA, F.ID_PRODUCTO, F.ID_SESION, F.NUM_SUBTOTAL, F.NUM_DESCUENTO, F.NUM_TOTAL, F.FECHA, F.ESTADO
    FROM TB_FACTURA AS F
    WHERE F.ESTADO = 1;
END