USE BDBubbleHouse;

CREATE TABLE TB_ROL(
	ID_ROL INT PRIMARY KEY IDENTITY(1,1),
	DSC_TIPO_ROL NVARCHAR(50),
	ESTADO TINYINT
)

CREATE TABLE TB_USUARIO(
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	ID_ROL INT,
	FOREIGN KEY (ID_ROL) REFERENCES TB_ROL(ID_ROL),
	DSC_NOMBRE NVARCHAR(50),
	DSC_PRIMER_APELLIDO NVARCHAR(50),
	DSC_SEGUNDO_APELLIDO NVARCHAR(50),
	DSC_CORREO NVARCHAR(50),
	DSC_PASSWORD NVARCHAR(50),
	FEC_REGISTRO DATETIME,
	DSC_TELEFONO NVARCHAR(50),
	ESTADO TINYINT
)


CREATE TABLE TB_SESION(
	ID_SESION INT PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT,
	FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
	DSC_SESION NVARCHAR(MAX),
	DSC_ORIGEN NVARCHAR(MAX),
	DSC_CIERRE NVARCHAR(MAX),
	FEC_INICIO DATETIME,
	FEC_CIERRE DATETIME, 
	ESTADO TINYINT
)