
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Obtener_SubCate_Productos_Activos
AS
BEGIN
    -- Seleccionar todos las subcategorías de productos cuyo estado sea diferente de 0
    SELECT SCP.ID_SUBCATE_PRODUCTO, SCP.ID_CATE_PRODUCTO_ID, SCP.DSC_NOMBRE_SUBCATEGORIA
    FROM TB_SUBCATEGORIA_PRODUCTO AS SCP
    WHERE SCP.ESTADO <> 0;
END
GO