
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Fernanda
-- Create date: 14-04-2024
-- Description:	Obtener Receta
-- =============================================
CREATE PROCEDURE Obtener_Receta
	


AS
BEGIN 
	SELECT * FROM TB_RECETA Re
	INNER JOIN TB_PRODUCTO AS Pro ON Re.ID_PRODUCTO = Pro.ID_PRODUCTO
	INNER JOIN TB_INGREDIENTE AS ING_Lac ON Re.ID_ING_LACTEO = ING_LAC.ID_INGREDIENTE
	INNER JOIN TB_INGREDIENTE AS ING_Sab ON Re.ID_ING_SABOR = ING_Sab.ID_INGREDIENTE
	INNER JOIN TB_INGREDIENTE AS ING_Azu ON Re.ID_ING_AZUCAR = ING_Azu.ID_INGREDIENTE
	INNER JOIN TB_INGREDIENTE AS ING_Topp ON Re.ID_ING_TOPPING = ING_Topp.ID_INGREDIENTE
	INNER JOIN TB_INGREDIENTE AS ING_Borde ON Re.ID_ING_BORDEADO = ING_Borde.ID_INGREDIENTE
	INNER JOIN TB_INGREDIENTE AS ING_Bubb ON Re.ID_ING_BUBBLES = ING_Bubb.ID_INGREDIENTE
	WHERE Re.ESTADO = 1
END
GO
